In [1]:
import torch
import numpy as np

In [2]:
torch.manual_seed(1)

In [3]:
model = lambda x, w, b: torch.matmul(x, w) + b

In [4]:
model

<function __main__.<lambda>(x, w, b)>

In [5]:
w = torch.randn(20, requires_grad=True)

In [6]:
b = torch.randn(1, requires_grad=True)

In [7]:
learning_rate = 1e-4

In [8]:
x = torch.rand(1000, 20)

In [9]:
y = x @ torch.tensor([0., 1] + [0] * 18) + 3.

In [10]:
y[:5]

tensor([3.2885, 3.8248, 3.1227, 3.4075, 3.5628])

In [11]:
y.shape

torch.Size([1000])

In [12]:
x[:5, :]

tensor([[0.9906, 0.2885, 0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471, 0.3556,
         0.4452, 0.0193, 0.2616, 0.7713, 0.3785, 0.9980, 0.9008, 0.4766, 0.1663,
         0.8045, 0.6552],
        [0.1768, 0.8248, 0.8036, 0.9434, 0.2197, 0.4177, 0.4903, 0.5730, 0.1205,
         0.1452, 0.7720, 0.3828, 0.7442, 0.5285, 0.6642, 0.6099, 0.6818, 0.7479,
         0.0369, 0.7517],
        [0.1484, 0.1227, 0.5304, 0.4148, 0.7937, 0.2104, 0.0555, 0.8639, 0.4259,
         0.7812, 0.6607, 0.1251, 0.6004, 0.6201, 0.1652, 0.2628, 0.6705, 0.5896,
         0.2873, 0.3486],
        [0.9579, 0.4075, 0.7819, 0.7165, 0.1768, 0.0748, 0.9799, 0.5261, 0.8427,
         0.6036, 0.6608, 0.8735, 0.9741, 0.1682, 0.5625, 0.8731, 0.8622, 0.8106,
         0.1381, 0.1399],
        [0.1976, 0.5628, 0.9983, 0.1842, 0.7664, 0.2233, 0.0299, 0.3937, 0.7881,
         0.9642, 0.1895, 0.6085, 0.9314, 0.8313, 0.8116, 0.8553, 0.8163, 0.6291,
         0.1581, 0.0801]])

In [13]:
for epoch in range(40_000):
    output = model(x, w, b)
    loss = (output.view(-1) - y.view(-1)).pow(2).mean()
    # print(output)
    # print(loss.item())
    loss.backward()
    # print(f'{w.grad=}')
    with torch.no_grad():
        w = w - learning_rate * w.grad
        b = b - learning_rate * b.grad
    # print(f'{w.grad=}')
    if epoch % 10_000 == 0:
        print(loss) # loss.item())
    w.requires_grad_(True)
    b.requires_grad_(True)

tensor(27.0643, grad_fn=<MeanBackward0>)
tensor(1.3977, grad_fn=<MeanBackward0>)
tensor(1.0463, grad_fn=<MeanBackward0>)
tensor(0.7941, grad_fn=<MeanBackward0>)


In [14]:
w

tensor([-0.4823,  0.4480,  0.1001, -0.4443,  0.7652,  0.5827, -0.0266,  0.7766,
         0.6334,  0.9162,  1.2457,  0.3381,  0.3601,  0.0699, -0.0675,  0.3579,
        -0.1323,  0.4685,  0.4810,  1.2350], requires_grad=True)

In [15]:
b

tensor([-0.3643], requires_grad=True)