In [1]:
import numpy as np
from pprint import pprint

In [2]:
mat = np.array(range(25)).reshape(5, -1)

In [3]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
def spiral_matrix(mat):
    rows, cols = mat.shape
    if rows < 1 or cols < 1:
        return
    yield from mat[0, :]
    yield from spiral_matrix(np.rot90(mat[1:,:]))

In [5]:
pprint(list(spiral_matrix(mat)), compact=True)

[0, 1, 2, 3, 4, 9, 14, 19, 24, 23, 22, 21, 20, 15, 10, 5, 6, 7, 8, 13, 18, 17,
 16, 11, 12]


In [6]:
xx, yy = np.indices((5, 5))

In [7]:
xx

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [8]:
yy

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [9]:
mat2 = np.empty((5, 5))

In [10]:
from itertools import count

c = count(1)
for row, col in zip(spiral_matrix(xx), spiral_matrix(yy)):
    mat2[row, col] = next(c)

In [11]:
mat2

array([[ 1.,  2.,  3.,  4.,  5.],
       [16., 17., 18., 19.,  6.],
       [15., 24., 25., 20.,  7.],
       [14., 23., 22., 21.,  8.],
       [13., 12., 11., 10.,  9.]])